"""Add new lead fields

Revision ID: 1728ecba01a4
Revises: a457a9f724e2
Create Date: 2026-03-25 11:10:55.085200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1728ecba01a4'
down_revision: Union[str, None] = 'a457a9f724e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('salutation', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('secondary_email', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('skype_id', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('website', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('title', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('tag', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('unsubscribed_mode', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('unsubscribed_time', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'unsubscribed_time')
    op.drop_column('leads', 'unsubscribed_mode')
    op.drop_column('leads', 'tag')
    op.drop_column('leads', 'rating')
    op.drop_column('leads', 'title')
    op.drop_column('leads', 'website')
    op.drop_column('leads', 'twitter')
    op.drop_column('leads', 'skype_id')
    op.drop_column('leads', 'secondary_email')
    op.drop_column('leads', 'salutation')
    # ### end Alembic commands ###
