"""add_advanced_crm_fields_v3

Revision ID: 2e72209901e7
Revises: 1728ecba01a4
Create Date: 2026-03-25 12:33:24.795611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e72209901e7'
down_revision: Union[str, None] = '1728ecba01a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_attachments_contact_id_contacts')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_attachments_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_notes_contact_id_contacts')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_notes_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lead_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_converted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('converted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_leads_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leads_owner_id_users'), type_='foreignkey')
        batch_op.drop_column('last_contacted_at')
        batch_op.drop_column('converted_at')
        batch_op.drop_column('is_converted')
        batch_op.drop_column('lead_score')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')
        batch_op.drop_column('subject')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
