"""Expand deals module schema with naming convention

Revision ID: aed5351ab0aa
Revises: a457a9f724e2
Create Date: 2026-03-25 12:19:53.460420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed5351ab0aa'
down_revision: Union[str, None] = 'a457a9f724e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_activities_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('closing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_stage_change', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_deals_account_id_accounts'), 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_deals_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deals_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_deals_account_id_accounts'), type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('account_id')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('last_stage_change')
        batch_op.drop_column('follow_up_date')
        batch_op.drop_column('closing_date')
        batch_op.drop_column('description')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activities_user_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
