"""add lead_id to deals and fix relationships

Revision ID: be45e1cfe245
Revises: aed5351ab0aa
Create Date: 2026-03-26 00:29:28.219468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be45e1cfe245'
down_revision: Union[str, None] = 'aed5351ab0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_deals_lead_id_leads'), 'leads', ['lead_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deals_lead_id_leads'), type_='foreignkey')
        batch_op.drop_column('lead_id')

    # ### end Alembic commands ###
